language: node_js
node_js:
  - "12"
cache:
  yarn: true

env:
  - GIT_USER=stkim92
#  - CURRENT_BRANCH=master
#  - USE_SSH=true
  
before_script:
  #  Setup
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - echo 'Testing!'
  - cd website
  - yarn run build
after_success:
  - yarn run publish-gh-pages
