language: node_js
node_js:
  - "12"
cache:
  yarn: true
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - echo 'Testing!'
  - cd website
  - yarn run build
after_success:
  - GIT_USER=stkim92 \
  CURRENT_BRANCH=master \
  USE_SSH=true \
  yarn run publish-gh-pages
