language: node_js
node_js:
  - "12"
cache:
  yarn: true
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - echo 'Testing!'
  - cd website
  - yarn install
after_success:
  - yarn run publish-gh-pages
